server:
  port: 8888
spring:
  application:
    name: optionsgenieconfig
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gokulr488/options-genie-configs.git
          default-label: master
          username: gokulr488
          password: ${ GITHUB_TOKEN }