server:
  port: 8888
spring:
  application:
    name: optionsgenieconfig
  cloud:
    config:
      server:
        git:
          uri: D:\personal\projects\optionsgenieconfig\src\main\resources\config